print("str(2.1) + str(1.2) => {}".format(str(2.1)+str(1.2)))
print("int(str(2)+str(3)) => {}".format(int(str(2)+str(3))))
print("str(int(12.3)) + '0' => {}".format(str(int(12.3)) + '0'))
print("int(’2’+’3’) => {}".format(int('2'+'3')))
print("str(2 + 3) => {}".format(str(2 + 3)))
print("str(int(2.1) + float(3)) => {}".format(str(int(2.1) + float(3))))