print("Convertidor de segundos a minutos")
segundos = int(input("Escriba una cantidad de segundos: "))
minutos = int(segundos / 60)
segs = segundos -(minutos * 60)
print("{} segundos son {} minutos y {} segundos".format(segundos, minutos, segs))